query About {
	about {
		...AboutFragment
	}
}

fragment AboutFragment on AboutRecord {
	text {
		value
		links
		blocks {
			__typename
			... on ImageBlockRecord {
				id
				image {
					...ImageFragment
				}
			}
		}
	}
	title
}
