query Course($slug: String!) {
	course(filter: { slug: { eq: $slug } }) {
		...CourseFragment
	}
}

query AllCourses($first: IntType = 500, $skip: IntType = 0) {
	allCourses(first: $first, skip: $skip) {
		...CourseFragment
	}
	_allCoursesMeta {
		count
	}
}

fragment CourseFragment on CourseRecord {
	id
	title
	text {
		blocks
		links
		value
	}
	slug
}

fragment CourseLightFragment on CourseRecord {
	id
	title
	slug
}
