query Exercise($slug: String!) {
	exercise(filter: { slug: { eq: $slug } }) {
		...ExerciseFragment
	}
}

query AllExercises($first: IntType = 500, $skip: IntType = 0) {
	allExercises(first: $first, skip: $skip) {
		...ExerciseFragment
	}
	_allExercisesMeta {
		count
	}
}

fragment ExerciseFragment on ExerciseRecord {
	id
	title
	intro {
		blocks
		links
		value
	}
	slug
	section {
		__typename
		id
		... on SectionExerciseRecord {
			headline
			exercise {
				__typename
				... on SovSoundExerciseItemRecord {
					id
					title
					file {
						...FileFragment
					}
					youtube {
						...VideoFieldFragment
					}
				}
				... on SofSoundExerciseItemRecord {
					id
					title
					file {
						...FileFragment
					}
					youtube {
						...VideoFieldFragment
					}
				}
			}
		}
	}
}
