query Start {
	start {
		...StartFragment
	}
	allUpcomingCourses(first: 2) {
		...UpcomingCourseLightFragment
	}
}

fragment StartFragment on StartRecord {
	text {
		blocks
		links
		value
	}
	text {
		blocks
		links
		value
	}
	logos {
		...MediaFragment
	}
}
