query Support($slug: String!) {
	support(filter: { slug: { eq: $slug } }) {
		...SupportFragment
	}
}

query AllSupports($first: IntType = 500, $skip: IntType = 0) {
	allSupports(first: $first, skip: $skip) {
		...SupportFragment
	}
	_allSupportsMeta {
		count
	}
}

fragment SupportFragment on SupportRecord {
	id
	sections {
		__typename
		... on SectionTextRecord {
			id
			content {
				value
				links
				blocks {
					__typename
					... on VideoBlockRecord {
						id
						youtube {
							...VideoFieldFragment
						}
					}
				}
			}
			title
		}
		... on SectionAppRecord {
			id
			appstore
			googleplay
			image {
				...ImageFragment
			}
			title
			text {
				blocks
				links
				value
			}
		}
	}
	title
	slug
}

fragment SupportLightFragment on SupportRecord {
	id
	title
	slug
	sections {
		__typename
		... on SectionTextRecord {
			id
			content {
				value
				links
				blocks {
					__typename
					... on VideoBlockRecord {
						youtube {
							...VideoFieldFragment
						}
					}
				}
			}
			title
		}
		... on SectionAppRecord {
			id
			appstore
			googleplay
			image {
				...ImageFragment
			}
			title
		}
	}
}
