query UpcomingCourse {
  upcomingCourse {
    ...UpcomingCourseFragment
  }
}

query AllUpcomingCourses($first: IntType = 500, $skip: IntType = 0) {
  allUpcomingCourses(first: $first, skip: $skip) {
    ...UpcomingCourseFragment
  }
  _allUpcomingCoursesMeta {
    count
  }
}

fragment UpcomingCourseFragment on UpcomingCourseRecord {
  city
  course {
    ... on CourseRecord {
      title
    }
  }
  date
}

fragment UpcomingCourseLightFragment on UpcomingCourseRecord {
  city
  course {
    ... on CourseRecord {
      title
    }
  }
  date
}
